version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: zSCALER#1999
      MYSQL_DATABASE: employeedb

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  employee-service:
    build: .

    container_name: employee-service

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zSCALER#1999

volumes:
  mysql-data: